# Generated by Django 3.1.2 on 2020-11-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.IntegerField(null=True)),
                ('Item_name', models.CharField(max_length=50, null=True)),
                ('Quantity', models.IntegerField(default='0', null=True)),
                ('Price', models.IntegerField(default='0', null=True)),
                ('Receive_qty', models.IntegerField(blank=True, default='0', null=True)),
                ('Receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Receive_from', models.CharField(blank=True, max_length=50, null=True)),
                ('Issue_qty', models.IntegerField(blank=True, default='0', null=True)),
                ('Issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Last_update', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockManager.category')),
            ],
            options={
                'verbose_name_plural': 'Stock Histories',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=50, null=True)),
                ('Quantity', models.IntegerField(default='0', null=True)),
                ('Price', models.IntegerField(default='0', null=True)),
                ('Added_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Receive_qty', models.IntegerField(blank=True, default='0', null=True)),
                ('Receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Receive_from', models.CharField(blank=True, max_length=50, null=True)),
                ('Issue_qty', models.IntegerField(blank=True, default='0', null=True)),
                ('Issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Last_update', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockManager.category')),
            ],
        ),
    ]
