# Generated by Django 3.1.2 on 2020-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='Category',
        ),
        migrations.AddField(
            model_name='stock',
            name='Rating',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
