# Generated by Django 3.1.2 on 2020-11-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockManager', '0002_auto_20201124_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Rage',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
