# Generated by Django 3.1.2 on 2020-11-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockManager', '0003_category_rage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Rage',
            new_name='Rate',
        ),
    ]
