# Generated by Django 3.1.2 on 2021-01-10 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockManager', '0004_auto_20201124_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'stocks', 'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'verbose_name': 'stocks history', 'verbose_name_plural': 'stocks history'},
        ),
        migrations.AddField(
            model_name='category',
            name='Last_update',
            field=models.DateTimeField(auto_now=True, help_text='Last update time of this item.', verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='category',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Created Time of this item.', verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(help_text='Category Name.', max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Rate',
            field=models.IntegerField(default='0', help_text='Category Rate.', null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Added_by',
            field=models.CharField(blank=True, help_text='Person or Worker who added this item.', max_length=50, null=True, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Category',
            field=models.ForeignKey(blank=True, help_text='Category of this item.', null=True, on_delete=django.db.models.deletion.CASCADE, to='StockManager.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Issue_by',
            field=models.CharField(blank=True, help_text='Person That issue quantity of this item.', max_length=50, null=True, verbose_name='Issue by'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Issue_qty',
            field=models.IntegerField(blank=True, default='0', help_text='The issue quantity of this item .', null=True, verbose_name='Issue quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Issue_to',
            field=models.CharField(blank=True, help_text='Person or Place that issue item to.', max_length=50, null=True, verbose_name='Issue to'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_name',
            field=models.CharField(help_text='Name of this item.', max_length=50, null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Last_update',
            field=models.DateTimeField(auto_now=True, help_text='Last update time of this item.', verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Price',
            field=models.IntegerField(default='0', help_text='Price of this item.', null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Quantity',
            field=models.IntegerField(default='0', help_text='Quantity of this item.', null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Rating',
            field=models.IntegerField(default='0', help_text='Rating value of this item.', null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Receive_by',
            field=models.CharField(blank=True, help_text='Person That receive quantity of this item.', max_length=50, null=True, verbose_name='Receive by '),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Receive_from',
            field=models.CharField(blank=True, help_text='Person or Place that receive item from.', max_length=50, null=True, verbose_name='Receive from'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Receive_qty',
            field=models.IntegerField(blank=True, default='0', help_text='The receive quantity of this item .', null=True, verbose_name='Receive quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Time of this item.', verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Issue_by',
            field=models.CharField(blank=True, help_text='Person That issue quantity of this item.', max_length=50, null=True, verbose_name='Issue by'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Issue_qty',
            field=models.IntegerField(blank=True, default='0', help_text='The issue quantity of this item .', null=True, verbose_name='Issue quantity'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Issue_to',
            field=models.CharField(blank=True, help_text='Person or Place that issue item to.', max_length=50, null=True, verbose_name='Issue to'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Item_id',
            field=models.IntegerField(help_text='Item id.', null=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Item_name',
            field=models.CharField(help_text='Name of this item.', max_length=50, null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Last_update',
            field=models.DateTimeField(auto_now=True, help_text='Last update time of this item.', verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Price',
            field=models.IntegerField(default='0', help_text='Price of this item.', null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Quantity',
            field=models.IntegerField(default='0', help_text='Quantity of this item.', null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Receive_by',
            field=models.CharField(blank=True, help_text='Person That receive quantity of this item.', max_length=50, null=True, verbose_name='Receive by '),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Receive_from',
            field=models.CharField(blank=True, help_text='Person or Place that receive item from.', max_length=50, null=True, verbose_name='Receive from'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Receive_qty',
            field=models.IntegerField(blank=True, default='0', help_text='The receive quantity of this item .', null=True, verbose_name='Receive quantity'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Time of this item.', verbose_name='Created Time'),
        ),
    ]
